version: '3.8'

networks:
  budgetbites:
    driver: bridge

services:
  postgres:
    image: postgres
    container_name: budgetbites-postgres
    environment:
      POSTGRES_DB: budgetbites
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5332:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./kupiapi/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - budgetbites
    restart: unless-stopped

  maildev:
    image: maildev/maildev
    container_name: budgetbites-maildev
    ports:
      - "1080:1080"  # Web interface
      - "1025:1025"  # SMTP server
    networks:
      - budgetbites
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: budgetbites-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@budgetbites.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - budgetbites
    restart: unless-stopped

volumes:
  postgres_data:
