version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: budgetbites-postgres
    environment:
      POSTGRES_DB: budgetbites
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5332:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

#  maildev:
#    image: maildev/maildev
#    container_name: budgetbites-maildev
#    ports:
#      - "1080:1080"  # Web interface
#      - "1025:1025"  # SMTP server
#    restart: unless-stopped

volumes:
  postgres_data:
